config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  root to: 'home#index'
  get '/about', to: 'home#about'
  get '/labs', to: 'home#labs'
  get '/contact', to: 'home#contact'

  resources :projects, only: [:index]
  resources :clients, only: [:index]

  namespace :admin do
    get 'dashboard', to: 'dashboard#index'
    resources :clients do
      get "delete"
    end
    resources :projects do
      get "delete"
    end
    resources :quotes do
      get "delete"
    end
  end
end

app/models/admin.rb
# == Schema Information
#
# Table name: admins
#
#  id                     :integer          not null, primary key
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#

class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/client.rb
# == Schema Information
#
# Table name: clients
#
#  id         :integer          not null, primary key
#  name       :string
#  url        :string
#  email      :string
#  phone      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Client < ActiveRecord::Base
  has_many :projects
  has_many :quotes

  has_attached_file :image, styles: { large: "1000x1000>", medium: "600x600>", thumb: "200x200>", icon: "60x60>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id          :integer          not null, primary key
#  title       :string
#  date        :date
#  description :text
#  featured    :boolean
#  url         :string
#  client_id   :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Project < ActiveRecord::Base
  belongs_to :client
  accepts_nested_attributes_for :client

  has_attached_file :image, styles: { large: "1000x1000>", medium: "600x600>", thumb: "200x200>", icon: "60x60>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :client
  accepts_nested_attributes_for :client
end

app/controllers/admin/clients_controller.rb
class Admin::ClientsController < AdminController
  before_action :all_clients, only: [:index, :create, :update, :destroy]
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  def index
  end

  def show
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.create(client_params)
  end

  def edit
  end

  def update
    @client.update_attributes(client_params)
  end

  def delete
    @client = Client.find(params[:client_id])
  end

  def destroy
    @client.destroy
  end

  private

  def set_client
    @client = Client.find(params[:id])
  end

  def all_clients
    @clients = Client.all
  end

  def client_params
    params.require(:client).permit(:id, :name, :url, :email, :phone, :image, :_destroy)
  end

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < AdminController
  before_action :all_clients, only: [:index]
  before_action :all_projects, only: [:index]
  before_action :all_quotes, only: [:index]

  def index
  end

  private

  def all_clients
    @clients = Client.all
  end

  def all_projects
    @projects = Project.all
  end

  def all_quotes
    @quotes = Quote.all
  end

end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < AdminController
  before_action :all_projects, only: [:index, :create, :update, :destroy]
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
  end

  def show
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.create(project_params)
  end

  def edit
  end

  def update
    @project.update_attributes(project_params)
  end

  def delete
    @project = Project.find(params[:project_id])
  end

  def destroy
    @project.destroy
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def all_projects
    @projects = Project.all
  end

  def project_params
    params.require(:project).permit(:id, :title, :date, :description, :featured, :url, :client_id, :image, :_destroy)
  end

end

app/controllers/admin/quotes_controller.rb
class Admin::QuotesController < AdminController
  before_action :all_quotes, only: [:index, :create, :update, :destroy]
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  def index
  end

  def show
  end

  def new
    @quote = Quote.new
  end

  def create
    @quote = Quote.create(quote_params)
  end

  def edit
  end

  def update
    @quote.update_attributes(quote_params)
  end

  def delete
    @quote = Quote.find(params[:quote_id])
  end

  def destroy
    @quote.destroy
  end

  private

  def set_quote
    @quote = Quote.find(params[:id])
  end

  def all_quotes
    @quotes = Quote.all
  end

  def quote_params
    params.require(:quote).permit(:id, :text, :client_id, :_destroy)
  end

end

app/controllers/admin_controller.rb
# Admin Controller, makes sure user is Admin before allowing access to Admin interface.
class AdminController < ApplicationController
  before_action :require_admin

  def index
  end

  private

  def require_admin
    unless admin_signed_in?
      redirect_to root_path
      flash[:notice] = "You must be a Site Administrator"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :all_clients, only: [:index]

  def index
  end

  private

  def all_clients
    @clients = Client.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @quotes = Quote.all
  end

  def about
  end

  def labs
  end

  def contact
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :all_projects
  
  def index
  end

  private

  def all_projects
    @projects = Project.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # STUB - Unfinshed ruby version of the slider.
  def featured_slider
    @projects = Projects.featured
    content_tag :li do
      @projects.each
    end
  end

end

app/views/admin/clients/_delete.html.erb
<div class="modal-content">
  Are you sure you want to delete <%= @client.name %>
</div>
<div class="modal-footer">
  <%= link_to "Yes, Delete this Client", admin_client_path(@client), method: :delete, remote: true, class: 'btn waves-effect waves-light red' %>
</div>

app/views/admin/clients/_edit.html.erb
<div class="modal-content">
  <h4><%= "Editing #{@client.name}" %></h4>
  <%= render 'form' %>
</div>

app/views/admin/clients/_form.html.erb
<div class="modal-content">
<ul class="errors"></ul>
  <%= form_for [:admin, @client], remote: true do |f| %>
    <%= f.label :image %>
    <%= f.file_field :image %>
    <br><br>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :url %>
    <%= f.text_field :url %>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <%= f.label :phone %>
    <%= f.text_field :phone %>
    <div class="modal-footer">
      <%= f.submit 'Submit', class: 'btn' %>
    </div>
  <% end %>
</div>

app/views/admin/clients/_new.html.erb
<div class="modal-content">
  <h4>New Client</h4>
<%= render 'form' %>
</div>

app/views/admin/clients/_save.js.erb
$("ul.errors").html("")
<% if @client.errors.any? %>
  <% @client.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $(".client-index").html("<%= escape_javascript(render 'admin/shared/client_index') %>")
  $("#client-modal").closeModal()
<% end %>

app/views/admin/clients/create.js.erb
<%= render 'save' %>

app/views/admin/clients/delete.js.erb
$("#client-modal").html("<%= escape_javascript(render 'delete') %>")
$("#client-modal").openModal()

app/views/admin/clients/destroy.js.erb
<%= render 'save' %>

app/views/admin/clients/edit.js.erb
$("#client-modal").html("<%= escape_javascript(render 'edit') %>")
$("#client-modal").openModal()

app/views/admin/clients/new.js.erb
$("#client-modal").html("<%= escape_javascript(render 'new') %>")
$("#client-modal").openModal()

app/views/admin/clients/update.js.erb
<%= render 'save' %>

app/views/admin/dashboard/index.html.erb
<div class="row">
  <div class="col s12">
    <div class="section">
      <ul class="tabs">
        <li class="tab col s4"><a href="#client">Clients</a></li>
        <li class="tab col s4"><a href="#project">Projects</a></li>
        <li class="tab col s4"><a href="#quote">Quotes</a></li>
        <li class="tab col s4"><a href="#service">Services</a></li>
      </ul>
    </div>
  </div>
  <div id="client">
    <%= render 'admin/shared/add_client' %>
  </div>
  <div id="project">
    <%= render 'admin/shared/add_project' %>
  </div>
  <div id="quote">
    <%= render 'admin/shared/add_quote' %>
  </div>
  <div id="service">
  PLACEHOLDER
    <%#= render 'admin/shared/add_service' %>
  </div>
</div>

app/views/admin/projects/_delete.html.erb
<div class="modal-content">
  Are you sure you want to delete <%= @project.title %>
</div>
<div class="modal-footer">
  <%= link_to "Yes, Delete this Project", admin_project_path(@project), method: :delete, remote: true, class: 'btn waves-effect waves-light red' %>
</div>

app/views/admin/projects/_edit.html.erb
<div class="modal-content">
  <h4><%= "Editing #{@project.title}" %></h4>
  <%= render 'form' %>
</div>

app/views/admin/projects/_form.html.erb
<div class="modal-content">
<ul class="errors"></ul>
  <%= form_for [:admin, @project], remote: true do |f| %>
    <%= f.label :image %>
    <%= f.file_field :image %>
    <br><br>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :date %>
    <%= f.date_field :date, class: 'datepicker' %>
    <%= f.label :client_id %>
    <%= f.collection_select :client_id, Client.all, :id, :name, class: 'browser-default' %>
    <%= f.label :description %>
    <%= f.text_area :description, class: 'materialize-textarea' %>
    <%= f.check_box :featured %>
    <%= f.label :featured %>
    <%= f.text_field :url %>
    <%= f.label :url %>
    <div class="modal-footer">
      <%= f.submit 'Submit', class: 'btn' %>
    </div>
  <% end %>
</div>

app/views/admin/projects/_new.html.erb
<div class="modal-content">
  <h4>New Project</h4>
<%= render 'form' %>
</div>

app/views/admin/projects/_save.js.erb
$("ul.errors").html("")
<% if @project.errors.any? %>
  <% @project.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $(".project-index").html("<%= escape_javascript(render 'admin/shared/project_index') %>")
  $("#project-modal").closeModal()
<% end %>

app/views/admin/projects/create.js.erb
<%= render 'save' %>

app/views/admin/projects/delete.js.erb
$("#project-modal").html("<%= escape_javascript(render 'delete') %>")
$("#project-modal").openModal()
$('.datepicker').pickadate()
$('select:not([multiple])').material_select()

app/views/admin/projects/destroy.js.erb
<%= render 'save' %>

app/views/admin/projects/edit.js.erb
$("#project-modal").html("<%= escape_javascript(render 'edit') %>")
$("#project-modal").openModal()
$('.datepicker').pickadate()
$('select:not([multiple])').material_select()

app/views/admin/projects/new.js.erb
$("#project-modal").html("<%= escape_javascript(render 'new') %>")
$("#project-modal").openModal()
$('.datepicker').pickadate()
$('select:not([multiple])').material_select()

app/views/admin/projects/update.js.erb
<%= render 'save' %>

app/views/admin/quotes/_delete.html.erb
<div class="modal-content">
  Are you sure you want to delete <%= @quote.id %>
</div>
<div class="modal-footer">
  <%= link_to "Yes, Delete this Quote", admin_quote_path(@quote), method: :delete, remote: true, class: 'btn waves-effect waves-light red' %>
</div>

app/views/admin/quotes/_edit.html.erb
<div class="modal-content">
  <h4><%= "Editing #{@quote.id}" %></h4>
  <%= render 'form' %>
</div>

app/views/admin/quotes/_form.html.erb
<div class="modal-content">
<ul class="errors"></ul>
  <%= form_for [:admin, @quote], remote: true do |f| %>
    <%= f.label :text %>
    <%= f.text_area :text %>
    <%= f.label :client %>
    <%= f.collection_select :client_id, Client.all, :id, :name %>
    <div class="modal-footer">
      <%= f.submit 'Submit', class: 'btn' %>
    </div>
  <% end %>
</div>

app/views/admin/quotes/_new.html.erb
<div class="modal-content">
  <h4>New Quote</h4>
<%= render 'form' %>
</div>

app/views/admin/quotes/_save.js.erb
$("ul.errors").html("")
<% if @quote.errors.any? %>
  <% @quote.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $(".quote-index").html("<%= escape_javascript(render 'admin/shared/quote_index') %>")
  $("#quote-modal").closeModal()
<% end %>

app/views/admin/quotes/create.js.erb
<%= render 'save' %>

app/views/admin/quotes/delete.js.erb
$("#quote-modal").html("<%= escape_javascript(render 'delete') %>")
$("#quote-modal").openModal()
$('select:not([multiple])').material_select()

app/views/admin/quotes/destroy.js.erb
<%= render 'save' %>

app/views/admin/quotes/edit.js.erb
$("#quote-modal").html("<%= escape_javascript(render 'edit') %>")
$("#quote-modal").openModal()
$('select:not([multiple])').material_select()

app/views/admin/quotes/new.js.erb
$("#quote-modal").html("<%= escape_javascript(render 'new') %>")
$("#quote-modal").openModal()
$('select:not([multiple])').material_select()

app/views/admin/quotes/update.js.erb
<%= render 'save' %>

app/views/admin/shared/_add_client.html.erb
<div class="section">
  <div class="container">
    <%= link_to 'Add Client', new_admin_client_path, remote: true, class: 'waves-effect waves-light btn-large red' %>
    <div class="new-client"></div>
  </div>
</div>
<div class="section">
  <div class="container">
    <table cellspacing="0" cellpadding="0" class="highlight">
      <thead>
        <tr>
          <th>ID</th>
          <th>Image</th>
          <th>Name</th>
          <th>Email</th>
          <th>URL</th>
          <th>Phone</th>
          <th>Controls</th>
        </tr>
      </thead>
      <tbody class="client-index">
        <%= render 'admin/shared/client_index' %>
      </tbody>
    </table>
  </div>
</div>
<div id="client-modal" class="modal"></div>

app/views/admin/shared/_add_project.html.erb
<div class="section">
  <div class="container">
    <%= link_to 'Add Project', new_admin_project_path, remote: true, class: 'waves-effect waves-light btn-large  red' %>
    <%= link_to 'Import Projects', '#', remote: true, class: 'waves-effect waves-light btn-large grey' %>
  </div>
</div>
<div class="section">
  <div class="container">
  <table cellpadding="0" cellspacing="0" class="highlight">
      <thead>
        <tr>
          <th>ID</th>
          <th>Image</th>
          <th>Title</th>
          <th>Date</th>
          <th>Description</th>
          <th>Client</th>
          <th>Featured?</th>
          <th>URL?</th>
          <th>Controls</th>
        </tr>
      </thead>
      <tbody class="project-index">
        <%= render 'admin/shared/project_index' %>
      </tbody>
    </table>
  </div>
</div>
<div id="project-modal" class="modal"></div>

app/views/admin/shared/_add_quote.html.erb
<div class="section">
  <div class="container">
    <%= link_to 'Add Quote', new_admin_quote_path, remote: true, class: 'waves-effect waves-light btn-large red' %>
    <div class="new-quote"></div>
  </div>
</div>
<div class="section">
  <div class="container">
    <table cellspacing="0" cellpadding="0" class="highlight">
      <thead>
        <tr>
          <th>ID</th>
          <th>Text</th>
          <th>Client</th>
        </tr>
      </thead>
      <tbody class="quote-index">
        <%= render 'admin/shared/quote_index' %>
      </tbody>
    </table>
  </div>
</div>
<div id="quote-modal" class="modal"></div>

app/views/admin/shared/_client_index.html.erb
<% @clients.each do |client| %>
  <tr>
    <td><%= client.id %></td>
    <td><%= image_tag client.image.url(:icon), class: 'responsive-img' %></td>
    <td><%= client.name %></td>
    <td><%= client.email %></td>
    <td><%= client.url %></td>
    <td><%= client.phone %></td>
    <td>
      <%= link_to 'Edit', edit_admin_client_path(client), remote: true, class: 'btn waves-effect waves-light' %>
      <%= link_to 'X', admin_client_delete_path(client), remote: true, class: 'btn waves-effect waves-light red' %>
    </td>
  </tr>
<% end %>

app/views/admin/shared/_project_index.html.erb
<% @projects.each do |project| %>
  <tr>
    <td><%= project.id %></td>
    <td><%= image_tag project.image.url(:icon), class: 'responsive-img' %></td>
    <td><%= project.title %></td>
    <td><%= project.date %></td>
    <td><%= project.description %></td>
    <td><%= project.client.name %></td>
    <td><%= project.featured ? 'Yes' : 'No' %></td>
    <td><%= project.url? ? 'Yes' : 'No' %></td>
    <td>
      <%= link_to 'Edit', edit_admin_project_path(project), remote: true, class: 'btn waves-effect waves-light' %>
      <%= link_to 'X', admin_project_delete_path(project), remote: true, class: 'btn waves-effect waves-light red' %>
    </td>
  </tr>
<% end %>

app/views/admin/shared/_quote_index.html.erb
<% @quotes.each do |quote| %>
  <tr>
    <td><%= quote.id %></td>
    <td><%= quote.text %></td>
    <td><%= quote.client.name %></td>
    <td>
      <%= link_to 'Edit', edit_admin_quote_path(quote), remote: true, class: 'btn waves-effect waves-light' %>
      <%= link_to 'X', admin_quote_delete_path(quote), remote: true, class: 'btn waves-effect waves-light red' %>
    </td>
  </tr>
<% end %>

app/views/clients/index.html.erb
<div class="container">
  <br />
  <div class="row section center-align">
    <div class="col s12 m12 l12"><h4>Our Recent Clients Include:</h4></div>
    <% @clients.each do |client| %>
      <div class="col s12 m4 l2 center-align">
        <ul>
          <li><%= image_tag client.image.url(:large), class: 'responsive-img white materialboxed circle', data: { caption: client.name } %></li>
          <li><%= client.name %></li>
          <li><%= link_to 'Website', "#{'http://'}" +  client.url, target: '_blank' %></li>
        </ul>
      </div>      
    <% end %>
  </div>
</div>

app/views/home/about.html.erb
<div class="container">
  <br />
  <div class="row">
    <div class="col s12 m12 l12 center-align">
      <h2>Mission Statement:</h2>
      <p><h4>We aren't here to reinvent the wheel, we are here to make it work better with different shapes.</h4></p>
    </div>
    <div class="col s12 m12 l12">
      <div class="col m5"><p><img src="http://placehold.it/300x300" alt="" class="responsive-img circle materialboxed"></p></div>
      <div class="col m7">
          <h3>Eugene Rasini</h3>
          <h5>Founder</h5>
          <a href="#" class="twitter">Twitter<span></span></a>
          <a href="#" class="linkedin">Linked In<span></span></a>
      </div>
    </div>
    <div class="col s12 m6 l6">
      <h4>Skills:</h4>
      <ul class="list">
        <li>Mastering Engineer</li>
        <li>Label Manager</li>
        <li>Music Producer</li>
        <li>Ideas Man</li>
        <li>Novice Ruby on Rails coder</li>
      </ul>
    </div>
    <div class="col s12 m6 l6">
      <h4>Work of Note:</h4>
      <ul>
        <li>Alexandra Palace Fireworks 2014 [Music Programming, Music Editing]</li>
        <li>Light Sounds Dark - WYWH [Mastering, Restoration, Consultation]</li>
        <li>CSL - The Chillout Album [Mastering]</li>
        <li></li>
      </ul>
    </div>
    <div class="col l12 s12 m12">
      <h4>References:</h4>
      <ul>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
      </ul>
    </div>
    <div class="col l12 s12 m12">
      <h4>Personal Words:</h4>
      <p>Having spent the last 18 years in the music industry; starting from humble, hardworking beginnings. I feel now is a good time to expand myself.</p>
      <p>Over the past few years </p>
    </div>      
  </div>
</div>

app/views/home/contact.html.erb
<div class="container">
  <h3>COMING SOON</h3>
</div>

app/views/home/index.html.erb
<%= render 'shared/slider' %>

<div class="section no-pad-bot" id="index-banner">
  <div class="container">
    <h2 class="header center red-text">Professional Services in Music &amp; Media</h2>
    <div class="row center">
      <h5 class="header col s12 light">We cover many aspects of the Music Industry. Check our site to see our latest Projects or some of the services we offer.</h5>
    </div>
    <div class="row center">
      <a href="services.html" id="download-button" class="btn-large waves-effect waves-light red darken-3">Find out More</a>
      <a href="contact.html" id="download-button" class="btn-large waves-effect waves-light red darken-3">Get In Touch</a>
    </div>
  </div>
</div>

<div class="container">
  <div class="section">
    <!--   Icon Section   -->
    <div class="row">
      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center red-text"><i class="mdi mdi-play"></i></h2>
          <h5 class="center">Professional Mastering</h5>

          <p class="light">Using a mix of the latest Digital Techonology and the warmth of Analogue gear, we can help you with all facets of your Mastering Needs.</p>
        </div>
      </div>

      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center red-text"><i class="mdi-social-group"></i></h2>
          <h5 class="center">Experienced Label Management</h5>

          <p class="light">With over 15 years Experience in the inductry, we have seen the transitional shift from Physical to Digital and back to some sort of strange equilibrium.</p>
        </div>
      </div>

      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center red-text"><i class="mdi mdi-beaker"></i></h2>
          <h5 class="center">Forward Thinking</h5>

          <p class="light">We never sit on our laurels here at Cromon, currently in the process of building a new content management system with Record Labels in mind, and other crazy disruptive ideas.</p>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render 'shared/quotes' %>

app/views/home/labs.html.erb
<div class="container">
  <h3>COMING SOON</h3>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CromonMediaSite</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'shared/nav' %>
<%= yield %>
<%= render 'shared/footer' %>

</body>
</html>

app/views/projects/index.html.erb
<div class="container">
  <div class="row">
    <br />
    <div class="col s12 m12 l12">Every year we work with lots of amazing and creative people, this section of the site is where we can showcase some of the more significant highlights of our work.</div>
  </div>
</div>

<div class="container">
  <div class="row">
  <br>
  <% @projects.each do |project| %>
    <div class="col s12 m12 l6">
      <div class="card large z-depth-2">
          <div class="card-image waves-effect waves-block waves-light white">
            <%= image_tag project.image.url(:large), class: 'activator responsive-img' %>
          </div>
          <div class="card-content">
            <span class="card-title activator grey-text text-darken-4"><%= project.title %><i class="mdi-navigation-more-vert right"></i></span>
            <p><%= link_to 'Link', "#{'http://'}" + project.url, target: '_blank' %>
          </div>
          <div class="card-reveal">
            <span class="card-title grey-text text-darken-4"><%= project.title %><i class="mdi-navigation-close right"></i></span>
            <p>
              <div>
                <ul>
                  <li><p><%= project.date.strftime('%B %Y') %></p></li>
                  <li><p><%= project.client.name %></p></li>
                  <li><p>TAGS TO DO!!</p></li>
                  <li><%= project.description.html_safe %></li>
                </ul>
              </div>
            </p>
          </div>
        </div>
    </div>
  <% end %>
  </div>
</div>  

app/views/shared/_nav.html.erb
<!-- Nav Component -->
<nav role="navigation">
  <div class="nav-wrapper container">
  <%= link_to image_tag("logo-text-only-white.png", class: 'responsive-img'), root_path, class: 'brand-logo', id: 'logo-container' %>
    <ul class="right hide-on-med-and-down">
      <li><a href="#">Services</a></li>
      <li><%= link_to 'Projects', projects_path %></li>
      <li><%= link_to 'Clients', clients_path %></li>
      <li><%= link_to 'Labs', labs_path %></li>
      <li><%= link_to 'Contact', contact_path %></li>
      <li><%= link_to 'About', about_path %></li>
      <% if admin_signed_in? %>
      <li><%= link_to 'Admin', admin_dashboard_path %></li>
      <li><%= link_to 'Logout', destroy_admin_session_path, method: :delete %></li>
      <% end %>
    </ul>

    <ul id="nav-mobile" class="side-nav">
      <li><%= link_to 'Projects', projects_path %></li>
      <li><%= link_to 'Clients', clients_path %></li>
      <li><%= link_to 'Labs', labs_path %></li>
      <li><%= link_to 'Contact', contact_path %></li>
      <li><%= link_to 'About', about_path %></li>
      <% if admin_signed_in? %>
      <li><%= link_to 'Admin', admin_dashboard_path %></li>
      <li><%= link_to 'Logout', destroy_admin_session_path, method: :delete %></li>
      <% end %>
    </ul>
    <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
  </div>
</nav>
<!-- Nav Component End -->

app/views/shared/_quotes.html.erb
<div class="section hide-on-med-and-down">
  <div class="container">
    <div class="row">
    <% @quotes.each do |quote| %>
      <div class="col m4">
        <blockquote class="card-panel">
          <%= quote.text %><br /><%= quote.client.name %>
        </blockquote>
      </div>
      <% end %>
    </div>
  </div>
</div>